billingApi:
  credentialId: "{BILLING_API_CREDENTIAL_ID}"
  credentialSecret: "{BILLING_API_CREDENTIAL_SECRET}"

mongo:
  uri: "mongodb://{MONGODB_PRIVATE_IP}:27017/billing"
  dbName: "billing"

objectStorage:
  endpoint: "https://objectstorage.kr-central-2.kakaocloud.com"
  bucket: "{OBJECT_STORAGE_BUCKET_NAME}"
  accessKey: "{OBJECT_STORAGE_ACCESS_KEY}"
  secretKey: "{OBJECT_STORAGE_SECRET_KEY}"


