billingApi:
  credentialId: "YOUR_BILLING_API_ID"
  credentialSecret: "YOUR_BILLING_API_SECRET"

mongo:
  uri: "mongodb://<MONGO_VM_INTERNAL_IP>:27017/billing"
  dbName: "billing"

objectStorage:
  endpoint: "https://objectstorage.kr-central-2.kakaocloud.com"
  bucket: "your-billing-raw-bucket"
  accessKey: "YOUR_ACCESS_KEY"
  secretKey: "YOUR_SECRET_KEY"


